dist: focal
language: minimal

cache:
  directories:
    # cmake project dependencies
    - .dependencies/
    # legacy PF-build dependencies
    - ./../PF-build-env/

before_install:
  # Prepare the dependencies for the old build environment
  - sudo apt-get install -y python3-polib python3-pyelftools python3-regex

  # Undo whatever *GARBAGE* travis is doing with python and restore the system version
  - mkdir -p .dependencies/python3
  - ln -sf /usr/bin/python3 .dependencies/python3/python3
  - PATH=$PWD/.dependencies/python3:$PATH

  # Bootstrap cmake/ninja for the new build environment
  - ./utils/bootstrap.py
  - PATH=$(./utils/bootstrap.py --print-dependency-directory "cmake")/bin:$PATH
  - PATH=$(./utils/bootstrap.py --print-dependency-directory "ninja"):$PATH

  # Arduino IDE adds a lot of noise caused by network traffic, firewall it off
  - sudo iptables -P INPUT DROP
  - sudo iptables -P FORWARD DROP
  - sudo iptables -P OUTPUT ACCEPT
  - sudo iptables -A INPUT -i lo -j ACCEPT
  - sudo iptables -A OUTPUT -o lo -j ACCEPT
  - sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

jobs:
  include:
    # legacy build.sh environment
    - stage: legacy
      script: ./.github/travis/legacy-build.sh

    # cmake-based build
    - stage: cmake
      script: ./.github/travis/cmake-build.sh

    # cmake tests
    - stage: tests
      script: ./.github/travis/cmake-test.sh

    # language checks
    - stage: lang
      script: ./.github/travis/cmake-lang.sh

stages:
  - cmake
  - lang
  - legacy
  - tests
