name: Feature request
description: Suggest new functionality
title: '[FEATURE REQUEST] '
labels:
  - feature request
body:
  - type: markdown
    attributes:
      value: |
        Before you create a new feature request, please check if an issue with it already exists (either open or closed) by using the search bar on the issues page.
  - type: checkboxes
    id: printer_model
    attributes:
      label: Printer model
      description: Select the printer model(s) where you would like this feature
      options:
        - label: MK3S/+
        - label: MK3
        - label: MK2.5S
        - label: MK2.5
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: How would this feature improve the printer? Are there specific use cases where this would be beneficial? Describe how you would use it.
    validations:
      required: true
  - type: textarea
    id: expected_functionality
    attributes:
      label: Expected functionality
      description: |
        Describe the way the feature would work. You can also describe it in a step-by-step basis if applicable.
