#include "preheat_data.h"
#include "eeprom.h"

// --- GENERATED BY utils/generate_preheat_data.py ---
// Variant: MK3S
// Source: PrusaSlicer INI + DEFAULT_TEMPS fallback

#if defined(PRINTER_VARIANT_MK3S) || defined(PRINTER_VARIANT_MK3)

const uint16_t preheat_hotend_temps[(uint8_t)MaterialIndex::_count][(uint8_t)NozzleCategory::_count] PROGMEM = {
    // {Default, 0.6mm, 0.8mm}
    {215, 215, 230},  // PLA
    {250, 240, 250},  // PETG
    {260, 260, 265},  // ASA
    {275, 275, 275},  // PC
    {215, 215, 225},  // PVB
    {275, 275, 275},  // PA
    {255, 255, 265},  // ABS
    {220, 220, 240},  // HIPS
    {254, 254, 254},  // PP
    {240, 240, 240},  // FLEX
    {230, 230, 230},  // VEGETAL
    {205, 205, 205},  // PLAPERL
    {205, 205, 205},  // PLABOIS
    {260, 260, 260},  // CLEAN1
    { 90,  90,  90},  // CLEAN2
};

const uint16_t preheat_bed_temps[(uint8_t)MaterialIndex::_count] PROGMEM = {
     60,  85, 105, 110,  75,  90, 100, 100, 100,  50,  60,  60,  60,   0,   0
};

#elif defined(PRINTER_VARIANT_MK25S) || defined(PRINTER_VARIANT_MK25)

// MK2.5 variants use same temperatures for now, except MK25_OVERRIDES
// (structure ready for future divergence)
const uint16_t preheat_hotend_temps[(uint8_t)MaterialIndex::_count][(uint8_t)NozzleCategory::_count] PROGMEM = {
    // {Default, 0.6mm, 0.8mm}
    {215, 215, 230},  // PLA
    {250, 240, 250},  // PETG
    {260, 260, 265},  // ASA
    {275, 275, 275},  // PC
    {215, 215, 225},  // PVB
    {275, 275, 275},  // PA
    {255, 255, 265},  // ABS
    {220, 220, 240},  // HIPS
    {254, 254, 254},  // PP
    {240, 240, 240},  // FLEX
    {230, 230, 230},  // VEGETAL
    {205, 205, 205},  // PLAPERL
    {205, 205, 205},  // PLABOIS
    {260, 260, 260},  // CLEAN1
    { 90,  90,  90},  // CLEAN2
};

const uint16_t preheat_bed_temps[(uint8_t)MaterialIndex::_count] PROGMEM = {
     60,  85, 105, 105,  75,  90, 100, 100, 100,  50,  60,  60,  60,   0,   0
};

#else
#error "No PRINTER_VARIANT_* defined"
#endif

NozzleCategory get_nozzle_category() {
    return nozzle_category_from_um(eeprom_read_word((uint16_t*)EEPROM_NOZZLE_DIAMETER_uM));
}

uint16_t get_preheat_hotend_temp(MaterialIndex material) {
    NozzleCategory cat = get_nozzle_category();
    return pgm_read_word(&preheat_hotend_temps[(uint8_t)material][(uint8_t)cat]);
}

uint16_t get_preheat_bed_temp(MaterialIndex material) {
    return pgm_read_word(&preheat_bed_temps[(uint8_t)material]);
}
